name: Build lavalink
on:
  schedule:
    - cron: "0 0 1 * 1"
  push:
    branches:
      - main
    paths:
      - bot/lavalink/*
      - .github/workflows/bot-lavalink.yml
jobs:
  push:
    name: "bot-lavalink"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./bot
          file: ./bot/lavalink/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:bot-lavalink