name: Build generic-debian
on:
  schedule:
    - cron: "0 0 1 * 1"
  push:
    branches:
      - main
    paths:
      - generic/debian/*
      - generic/entrypoint.sh
      - .github/workflows/generic-debian.yml
jobs:
  push:
    name: "generic-debian"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./generic
          file: ./generic/debian/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:generic-debian