name: Build nodejs-13
on:
  schedule:
    - cron: "0 0 1 * 1"
  push:
    branches:
      - main
    paths:
      - nodejs/nodejs-13/*
      - nodejs/entrypoint.sh
      - .github/workflows/*
jobs:
  push:
    name: "nodejs-13"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/nodejs-13/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:nodejs-13