name: Build nodejs-12
on:
  push:
    branches:
      - main
    paths:
      - nodejs/nodejs-12/*
      - nodejs/entrypoint.sh
      - .github/workflows/nodejs-12.yml
jobs:
  push:
    name: "nodejs-12"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./nodejs
          file: ./nodejs/nodejs-12/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:nodejs-12