name: Build python-3.10
on:
  schedule:
    - cron: "0 0 1 * 1"
  push:
    branches:
      - main
    paths:
      - python/python-3.10/*
      - python/entrypoint.sh
      - .github/workflows/python-3.10.yml
jobs:
  push:
    name: "python-3.10"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./python
          file: ./python/python-3.10/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:python-3.10