name: Build wine-generic
on:
  push:
    branches:
      - main
    paths:
      - wine/wine-generic/*
      - wine/entrypoint.sh
      - .github/workflows/wine-generic.yml
jobs:
  push:
    name: "wine-generic"
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./wine
          file: ./wine/wine-generic/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:wine-generic